FROM docker.io/library/archlinux

RUN yes | pacman -Sy git

RUN git clone https://github.com/kworkflow/kworkflow /opt/kw

WORKDIR /opt/kw

RUN yes | ./setup.sh --install

# vim: set filetype=dockerfile :
