FROM docker.io/library/fedora

RUN dnf install -y git

RUN git clone https://github.com/kworkflow/kworkflow /opt/kw

WORKDIR /opt/kw

RUN ./setup.sh --install --force

# vim: set filetype=dockerfile :
